
= Spring Boot Starter for Bucket4j

https://github.com/vladimir-bukhtoyarov/bucket4j

*Examples:*
https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples[bucket4j-spring-boot-starter-examples]

This project provides an integration of bucket4j for limiting the rate of access to REST APIs.
To limit the access of requests this projects provides predefined filter types which can be reused for simple configurations options.

It autoconfigures servlet filter via property files.

== Autoconfiguration:

* Detects the CachManger(JCache) and configures it for bucket4j. You can configure the different CacheManager with https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html[spring-boot-starter-cache]
* Servlet filter registration for limiting the rate
* Configuration via properties
** cache name
** url
** multiple bandwith (capacity, time unit)
** predefined filter types
 


=== Filter types (bad name, should be renamed in the feature)

Filter types are predefined configuration option on how to define the key which should be used to limiting the requests.

==== Default

The default options doesn't differentiates between incoming requests (user, ip, etc). Its a general limiting.

==== IP

The IP filter type limits the access based on the IP address (httpServletRequest.getRemoteAddr()). So each IP address will independently throttled.

==== Expression

The expression based filter type provides the most flexible one but uses the Spring Expression Language (SpEL) which is maybe not the best choice for optimal performance.
But is provides an easy way to configure the limiting in different environments without writing one line of code.

*Limiting based on IP-Address*:
[source]
----
getRemoteAddress()
----


*Limiting based on Username - If not logged in use IP-Address*:
[source]
----
@securityService.username()?: getRemoteAddr()
----
[source,java]
----
@Service
public class SecurityService {

	public String username() {
		String name = SecurityContextHolder.getContext().getAuthentication().getName();
		if(name == "anonymousUser") {
			return null;
		}
		return name;
	}
	
}
----
 

== Configuration via properties

[source,yml]
----
bucket4j:
  rate-limit:
    enabled: true
    filter-method: servlet # servlet(default), zuul
    configs:
    - cache-name: buckets   # create new servlet filter with bucket4j configuration
      filter-type: default  # filter all requests indipendently from the source
      url: /*
      bandwidths: 
      - # maximum of 5 requests within 10 seconds
        capacity: 5
        time: 10
        unit: seconds  
    - cache-name: buckets
      filter-type: ip			# ip based filter
      url: /abc*
      bandwidths: 
      -
        capacity: 5
        time: 10
        unit: seconds
    - cache-name: buckets
      filter-type: expression  # expression based filter key evaluation
      expression: "@securityService.username()?: getRemoteAddr()" # use the username as key. if authenticated use the ip address
      url: /*
      filter-order: 0
      bandwidths: 
      -
        capacity: 5
        time: 10
        unit: seconds    
----

== Configuration via @Bean

