@startuml

User -> Bucket4jFilter: request

box "Webserver" #f5e4e4

    Bucket4jFilter -> Bucket4jFilter : estimate_remaining_tokens
    participant Bucket4jFilter
    participant SpringSecurityFilter
    alt 1 token available

        note right of Bucket4jFilter: There is one token available. \nThe request will not be aborted
        Bucket4jFilter -> SpringSecurityFilter : request
        SpringSecurityFilter -> SpringSecurityFilter : authenticate
        SpringSecurityFilter -> Bucket4jFilter : response(401)
        alt HTTP Response Status == 401
            note right of Bucket4jFilter: The token will only  be consumed\n if the HTTP Status is 401\n
            Bucket4jFilter -> Bucket4jFilter : consume_token
        end
        Bucket4jFilter -> User : response(401)

    else 0 token available
        note right of Bucket4jFilter: The token was consumed \nbecause of the HTTP Response Status 401
        Bucket4jFilter -> Bucket4jFilter : reject request
        Bucket4jFilter -> User : response\n(429 Too Many Requests)
    end





end box


@enduml