debug: false
logging:
  level:
    com.giffing.bucket4j: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

bucket4j:
  enabled: true
  cache-to-use: redis-jedis
  filter-config-caching-enabled: true
  filter-config-cache-name: filterConfigCache
  filters:
    - cache-name: buckets_test
      major-version: 2
      url: ^(/hello).*
      id: filter1
      rate-limits:
        - tokens-inheritance-strategy: reset
          bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
              refill-speed: interval
    - cache-name: buckets_test
      url: ^(/world).*
      id: filter2
      rate-limits:
        - tokens-inheritance-strategy: reset
          bandwidths:
            - capacity: 10
              time: 10
              unit: seconds
              refill-speed: interval
  methods:
    - name: method_test
      cache-name: greetings
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 30
            unit: seconds
            refill-speed: interval
  default-metric-tags:
    - key: IP
      expression: "getRemoteAddr()"
      types:
        - REJECTED_COUNTER
        - CONSUMED_COUNTER
        - PARKED_COUNTER
        - INTERRUPTED_COUNTER
        - DELAYED_COUNTER
  default-method-metric-tags:
    - key: IP
      expression: "@testServiceImpl.getRemoteAddr()"
      types:
        - REJECTED_COUNTER
        - CONSUMED_COUNTER
        - PARKED_COUNTER
        - INTERRUPTED_COUNTER
        - DELAYED_COUNTER
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379

