spring:
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
  main:
    allow-bean-definition-overriding: true
bucket4j:
  enabled: true
  filter-config-caching-enabled: true
  filter-config-cache-name: filterConfigCache
  filters:
  - id: filter1
    cache-name: buckets
    url-pattern: .*
    major-version: 1
    rate-limits:
    - tokens-inheritance-strategy: reset
      skip-condition: "getRequestURI().contains('filter')"
      bandwidths:
      - capacity: 5
        time: 10
        unit: seconds
        refill-speed: interval