logging:
  level:
    com.giffing.bucket4j: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

bucket4j:
  enabled: true
  cache-to-use: redis-redisson
  filter-config-caching-enabled: true
  filter-config-cache-name: filterConfigCache
  filters:
    - id: filter1
      major-version: 1
      cache-name: buckets_test
      filter-method: webflux
      url-pattern: ^(/hello).*
      rate-limits:
        - tokens-inheritance-strategy: reset
          bandwidths:
            - id: bandwidth1
              capacity: 5
              time: 10
              unit: seconds
              refill-speed: interval
    - id: filter2
      major-version: 1
      cache-name: buckets_test
      filter-method: webflux
      url-pattern: ^(/world).*
      rate-limits:
        - tokens-inheritance-strategy: reset
          bandwidths:
            - id: bandwidth3
              capacity: 10
              time: 10
              unit: seconds
              refill-speed: interval

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
