logging:
  level:
    com.giffing.bucket4j.spring.boot.starter: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cache:
    type: infinispan
infinispan:
  embedded:
    config-xml: infinispan.xml
bucket4j:
  enabled: true
  filter-config-caching-enabled: true
  filter-config-cache-name: filterConfigCache
  filters:
  - id: filter1
    cache-name: buckets
    filter-method: webflux
    url-pattern: .*
    http-content-type: application/json;charset=UTF-8
    http-response-body: '{ "name": "hello"}'
    http-response-headers:
      HELLO: WORLD
    filter-order: 1
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 10
        unit: seconds
